// <auto-generated />
using System;
using LotTrackerApp.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LotTrackerApp.Migrations
{
    [DbContext(typeof(LoteTrackerDbContext))]
    [Migration("20211217112456_LoteTracker v2")]
    partial class LoteTrackerv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LotTrackerApp.Data.Entities.Paises", b =>
                {
                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("LotTrackerApp.Data.Entities.ProdutoFabricante", b =>
                {
                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fabricante")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Produto", "Fabricante");

                    b.HasIndex("Pais1");

                    b.ToTable("ProdutoFabricante");
                });

            modelBuilder.Entity("LotTrackerApp.Data.Entities.ProdutoLote", b =>
                {
                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DtFabrico")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fabricante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Produto", "Lote");

                    b.ToTable("ProdutoLote");
                });

            modelBuilder.Entity("LotTrackerApp.Data.Entities.Produtos", b =>
                {
                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Produto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("LotTrackerApp.Data.Entities.ProdutoFabricante", b =>
                {
                    b.HasOne("LotTrackerApp.Data.Entities.Paises", "Pais")
                        .WithMany()
                        .HasForeignKey("Pais1");

                    b.Navigation("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
